// Automatically created by src/iris/makefile -- DO NOT CHANGE!!!
var IRIS_EEPROM = {};
IRIS_EEPROM.DEFS = {
    CONNECTIVITY_AUTO: 0,
    CONNECTIVITY_WIRED: 1,
    CONNECTIVITY_WIRELESS: 2,
    EEPROM_BATTERY_ADC4MIN: 444,
    EEPROM_BATTERY_SCALE: 2,
    EEPROM_CURRENT_MAGIC: 165,
    EEPROM_CURRENT_VERSION: 3,
    EEPROM_OFF_BATTERY_ADC4MIN: 11,
    EEPROM_OFF_BATTERY_SCALE: 13,
    EEPROM_OFF_CONNECTIVITY: 10,
    EEPROM_OFF_END: 28,
    EEPROM_OFF_ETHERNET_ADDR: 14,
    EEPROM_OFF_ETHERNET_GWAR: 24,
    EEPROM_OFF_ETHERNET_PORT: 18,
    EEPROM_OFF_ETHERNET_SUBR: 20,
    EEPROM_OFF_EUI: 2,
    EEPROM_OFF_MAGIC: 0,
    EEPROM_OFF_TABLE: 10,
    EEPROM_OFF_VERSION: 1,
    EEPROM_TABLE_LEN: 18,
};
