//  (C) COPYRIGHT INTERNATIONAL BUSINESS MACHINES CORPORATION 2006-2010
//                       ALL RIGHTS RESERVED
//        IBM Research Division, Zurich Research Laboratory
// --------------------------------------------------------------------


/**
 * @class Bugz.Frame encapsulates a frame.
 * @constructor
 * @param idx
 * @param pc
 */
Bugz.Frame = function(/** SOnoran.Mote */mote, /** Number */idx, /** Bugz.PC */pc) {
    this.mote = mote;
    this.idx = idx;
    this.pc = pc;
    this.locals = [];
};

/** @private */
Bugz.Frame.prototype = {
      /** @ignore */
    __constr__: "Bugz.Frame",
    
    /**
     * @type Sonoran.Mote
     */
    mote: null,
    
    /**
     * @type Number
     */
    idx: -1,

    /**
     * @type Bugz.PC
     */
    pc: null,

    /**
     * @type Bugz.Slot[]
     */
    locals: null,

    
    /**
     * @returns {String}
     */
    toString: function() {
        return this.getInfo();
    },


    /**
     * Add frame info to table generated by stack.
     * @param t
     */
    addInfo: function(/** Util.Formatter.Table2 */t) {
        var fid = this.idx.toString();
        var info = this.pc.getInfo();
        var fpc = info.fspec ? info.fspec : info.pc;
        var cls = info.cspec ? info.cspec : "";
        if (this.locals==null||this.locals.length==0) {
            t.addRow(fid, fpc, "---", "---", "---", "---", cls);
        } else {
            for (var i = 0; i < this.locals.length; i++) {
                var l = this.locals[i];
                if (i == 0) {
                    t.addRow(fid, fpc, l.getName()||"Unknown", l.getValue(), l.getSlot(), l.getType(), cls);
                } else {
                    t.addRow("",  "",  l.getName()||"Unknown", l.getValue(), l.getSlot(), l.getType(), "");
                }
            }
        }
    },

    
   /**
     * @returns {String}
     */
    getInfo: function() {
	var t = new Formatter.Table2(7);
	t.setTitle("F#", "PC", "Name", "Value", "Slot", "Type", "Class    " + this.mote.getUniqueid());
        this.addInfo(t);
        return  t.render().join("\n");
    },
    

    /**
     * @returns {Bugz.Slot[]} the local variables
     */
    getLocals: function() {
        return this.locals;
    }
};
